version: '2'

services:
  inventario_front:
    image: trion/ng-cli:9.1.5
    ports:
      - 4300:4200
    volumes:
     - ./:/app
    command: ["ng", "serve", "--host", "0.0.0.0", "--disable-host-check"]
